#page title
page_title                                : Form Builder Pro | Make forms and fill them out on your iPad    # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Create forms and fill them out on your iPad

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Wander Bit LLC                              
your_link                                 : https://wanderbit.com                     
your_city                                 : New York                                
email_address                             : info@wanderbit.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Create Forms
    description                           : Create forms with multiple choice, text questions, signature pages, photo pages, and more.
    fontawesome_icon_name                 : magic
    
  - title                                 : Fill Out Forms
    description                           : Customers, clients, and employees complete forms on your device.
    fontawesome_icon_name                 : mobile

  - title                                 : View Reponses
    description                           : View responses within the app, export responses to other apps, or have the app email you any time you get a new response.
    fontawesome_icon_name                 : play-circle

  - title                                 : Great For Trade Shows
    description                           : Use Form Builder Pro at your next trade show to gather valuable leads at your booth.
    fontawesome_icon_name                 : sync

  - title                                 : Great For Reception Desks
    description                           : Keep a record of visitors to your office or business by deploying a form on an iPad at the reception desk.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Great for Real Estate Agents
    description                           : Ditch pencil and paper at your next open house and use Form Builder Pro as your sign in sheet.
    fontawesome_icon_name                 : star



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown